<a href="https://colab.research.google.com/github/anuvishalp/Python_basics/blob/main/Python_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35],
    "City": ["New York", "San Francisco", "Los Angeles"]
}

df = pd.DataFrame(data)
df

      Name  Age           City
0    Alice   25       New York
1      Bob   30  San Francisco
2  Charlie   35    Los Angeles

In [ ]:
"""View basic info

df.info()

Summary statistics

df.describe()

Select a column

df["Name"]

Filter rows

df[df["Age"] > 28]

Add a new column

df["Age_in_5_years"] = df["Age"] + 5 """

In [ ]:
"""Pandas is mainly used for datacleaning
data manipulation
exploratory data analysis
data visualization
machine learning """

In [ ]:
#create a data frame of students, rollno, marks,subject .Print the dataframe.
#accessing the elements

df1={
    "students":["app","bob","cap","dad"],
    "rollno":[1,2,3,4],
    "marks":["10","20","30","40"],
    "subject":["science","social","maths","physics"]
}

df=pd.DataFrame(df1)
df

  students  rollno marks  subject
0      app       1    10  science
1      bob       2    20   social
2      cap       3    30    maths
3      dad       4    40  physics

In [ ]:
##🔹 Slicing rows -> Using index-based slicing on a DataFrame:

df[0:2]   # rows 0 and 1
df[1:2]   # row 1 only
df[0:]    # from row 0 to end
df[1:]    # from row 1 to end

  students  rollno marks  subject
1      bob       2    20   social
2      cap       3    30    maths
3      dad       4    40  physics

In [ ]:
##🔹 Filtering rows -> Boolean filtering based on column values:

df[df["Age"] > 25]
df
##df[df["City"] == "New York"]

      Name  Age           City
0    Alice   25       New York
1      Bob   30  San Francisco
2  Charlie   35    Los Angeles

In [ ]:
##🔹 Handling missing data ->Checking, dropping, or filling missing values:

##df.isnull() -> boolean output
##df.dropna()
df.fillna(0)

      Name  Age           City
0    Alice   25       New York
1      Bob   30  San Francisco
2  Charlie   35    Los Angeles

In [ ]:
##🔹 Sorting -> The comment suggests sorting is next, likely something like:

df.sort_values(by="Age")

      Name  Age           City
0    Alice   25       New York
1      Bob   30  San Francisco
2  Charlie   35    Los Angeles

In [ ]:
##🔹 Filtering (Boolean indexing)

df[df["Age"] > 25]
df[df["City"] == "New York"]

##Great for row-level conditions ->Can combine multiple conditions with & and | (wrapped in parentheses)

##🔹 Handling missing data

df.isnull()        # Boolean mask of missing values
df.dropna()        # Remove rows with any missing values
df.fillna(0)       # Replace missing values with 0

##Useful variations:

df.dropna(subset=["Age"])

df.fillna({"Age": df["Age"].mean()})

##🔹 Sorting
df.sort_values(by="Age")
df.sort_values(by="Age", ascending=False)

##You can sort by multiple columns:

df.sort_values(by=["City", "Age"])

##🔹 Grouping (aggregation)

df.groupby("Age").mean(numeric_only=True)
df.groupby("City").sum()

##More expressive patterns:

df.groupby("City")["Age"].mean()
df.groupby("City").agg({"Age": "mean", "Salary": "sum"})

In [ ]:
##Create a sample DataFrame -> import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie", "Diana", "Evan"],
    "Department": ["HR", "Engineering", "Engineering", "HR", "Finance"],
    "Salary": [60000, 95000, 88000, 62000, 72000],
    "Age": [29, 35, 41, 26, 30]
}

df = pd.DataFrame(data)
df

      Name   Department  Salary  Age
0    Alice           HR   60000   29
1      Bob  Engineering   95000   35
2  Charlie  Engineering   88000   41
3    Diana           HR   62000   26
4     Evan      Finance   72000   30

In [ ]:
##📊 Average salary by department
df.groupby("Department")["Salary"].mean()

Department
Engineering    91500.0
Finance        72000.0
HR             61000.0
Name: Salary, dtype: float64

In [ ]:
##🔽 Sort by age (youngest first)
df.sort_values(by="Age", ascending=True)

      Name   Department  Salary  Age
3    Diana           HR   62000   26
0    Alice           HR   60000   29
4     Evan      Finance   72000   30
1      Bob  Engineering   95000   35
2  Charlie  Engineering   88000   41

In [ ]:
df.sort_values(by=["age","name"])

In [ ]:
df.groupby("Age").mean(numeric_only=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        5 non-null      object
 1   Department  5 non-null      object
 2   Salary      5 non-null      int64
 3   Age         5 non-null      int64
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes

In [ ]:
df.describe()

             Salary        Age
count      5.000000   5.000000
mean   75400.000000  32.200000
std    15582.040945   5.890671
min    60000.000000  26.000000
25%    62000.000000  29.000000
50%    72000.000000  30.000000
75%    88000.000000  35.000000
max    95000.000000  41.000000

In [ ]:
"""
⭐ Multiple Ways to Calculate Average in pandas
=======================================================

1️⃣ Column Mean (most common)

df["Age"].mean()

Computes the average of a single column.

df["Age"].mean()

2️⃣ DataFrame Mean (all numeric columns)
df.mean() ->Returns mean for every numeric column.

python
df.mean(numeric_only=True)
3️⃣ Group-wise Mean
df.groupby("City")["Age"].mean()
Average Age per City.

python
df.groupby("City")["Age"].mean()
Multiple aggregations:
python
df.groupby("City").agg({"Age": "mean", "Salary": "mean"})
4️⃣ Mean with agg()
df.agg("mean")
Applies mean across all numeric columns.

python
df.agg("mean")
Or for specific columns:

python
df.agg({"Age": "mean"})
5️⃣ Using describe() (mean included)
df["Age"].describe()
Gives count, mean, std, min, quartiles, max.

python
df["Age"].describe()
6️⃣ Weighted Average (custom)
Pandas doesn’t have a built‑in weighted mean, but you can compute it easily:

python
import numpy as np
np.average(df["Age"], weights=df["Salary"])
7️⃣ Mean after filtering
Average of a subset:

python
df[df["City"] == "New York"]["Age"].mean()
8️⃣ Mean ignoring missing values (default behavior)
Pandas automatically ignores NaN:

python
df["Age"].mean()
But you can enforce it:

python
df["Age"].mean(skipna=True)
9️⃣ Mean using .loc or .iloc
python
df.loc[:, "Age"].mean()
df.iloc[:, 3].mean()   # if Age is 4th column
🔟 Mean using apply()
(Not recommended for performance, but useful for teaching)

python
df.apply(lambda col: col.mean())
1️⃣1️⃣ Rolling Mean (moving average)
Useful for time series:

python
df["Age"].rolling(window=3).mean()
1️⃣2️⃣ Expanding Mean (cumulative average)
python
df["Age"].expanding().mean() """

In [ ]:
"""
1️⃣ df = pd.read_csv("data.csv")
Loads a CSV file into a pandas DataFrame.

Rows → records

Columns → fields

This is usually the first step in any data‑analysis workflow.

2️⃣ df.head()
Shows the first 5 rows.

Useful for: sanity‑checking the data
            confirming column names
            spotting obvious issues

You can also specify a number:

df.head(10)

3️⃣ df.tail() ->Shows the last 5 rows.

Great for: checking if the file loaded fully
          inspecting trailing values
          seeing if there are footer rows or junk at the end

4️⃣ df.info()
Displays:

column names

data types

number of non‑null values

memory usage

This is your data health report — perfect for spotting missing values or wrong data types.

5️⃣ df.duplicated() -> Returns a Boolean Series indicating which rows are duplicates.

Example output:

Code
0    False
1    False
2    True
3    False
6️⃣ df.drop_duplicates() -> Removes duplicate rows.

You can also specify columns:

df.drop_duplicates(subset=["Name", "Age"])

Or keep the last occurrence:

df.drop_duplicates(keep="last")

7️⃣ df.rename(columns={"old_name": "new_name"}) ->Renames one or more columns.

Example:

df.rename(columns={"Salary": "AnnualSalary"})

To rename multiple:

df.rename(columns={"Name": "EmployeeName", "Age": "EmployeeAge"}) """

In [ ]:
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve"],
    "Subject": ["Maths", "Hindi", "English", "Science", "Accounts"],
    "Marks": [90, 85, 92, 88, 95]
}

df = pd.DataFrame(data)
df

      Name   Subject  Marks
0    Alice     Maths     90
1      Bob     Hindi     85
2  Charlie   English     92
3    David   Science     88
4      Eve  Accounts     95

In [ ]:
#Filter students who scored 80 or above
df[df["Marks"] >= 80]

      Name   Subject  Marks
0    Alice     Maths     90
1      Bob     Hindi     85
2  Charlie   English     92
3    David   Science     88
4      Eve  Accounts     95

In [ ]:
##2️⃣ Using query()

df.query("Marks >= 80")

      Name   Subject  Marks
0    Alice     Maths     90
1      Bob     Hindi     85
2  Charlie   English     92
3    David   Science     88
4      Eve  Accounts     95

In [ ]:
##3️⃣ Using loc
df.loc[df["Marks"] >= 80]

In [ ]:
##4️⃣ Filtering + selecting only names
df.loc[df["Marks"] >= 80, "Name"]

In [ ]:
##5️⃣ Filtering + selecting multiple columns
df.loc[df["Marks"] >= 80, ["Name", "Marks"]]